#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'build-essential'
cookbook 'ruby_build', git: 'https://github.com/fnichol/chef-ruby_build.git'
cookbook 'rbenv', git: 'https://github.com/fnichol/chef-rbenv.git'
cookbook 'postgresql', git: 'https://github.com/thomas88/postgresql.git', ref: 'default-value-for-ssl-files'
cookbook 'database', :git => 'git://github.com/manuelvanrijn/cookbook-database.git', :ref => 'grant-roles'
